std = "lua51"
max_line_length = 120
exclude_files = { "tools/.cache/**", ".release/**" }
ignore = { "212/_.*" } -- unused args prefixed with _
globals = {
	"FerryForeverCharDB",
	"FerryForeverDB",
	"FerryForeverDockPinMixin",
	"FerryForeverGoalPinMixin",
	"FerryForeverPortalPinMixin",
	"FerryForeverRoutePinMixin",
	"SLASH_FERRYFOREVER1",
	"SlashCmdList",
}
read_globals = {
	"AM_PIN_SCALE_STYLE_WITH_TERRAIN",
	"Ambiguate",
	"C_ChatInfo",
	"Clamp",
	"Lerp",
	"Menu",
	"Saturate",
	"C_Map",
	"C_Timer",
	"CreateFrame",
	"CreateFromMixins",
	"CreateVector2D",
	"Enum",
	"EPIC_PURPLE_COLOR",
	"GameTooltip",
	"GameTooltip_AddColoredDoubleLine",
	"GameTooltip_AddColoredLine",
	"GameTooltip_AddNormalLine",
	"GameTooltip_SetTitle",
	"geterrorhandler",
	"GetNormalizedRealmName",
	"GetRealmName",
	"GetServerTime",
	"GetTime",
	"GRAY_FONT_COLOR",
	"HIGHLIGHT_FONT_COLOR",
	"hooksecurefunc",
	"IsInGroup",
	"IsInGuild",
	"IsInInstance",
	"IsInRaid",
	"LE_PARTY_CATEGORY_INSTANCE",
	"LIGHTBLUE_FONT_COLOR",
	"MapCanvasDataProviderMixin",
	"MapCanvasPinMixin",
	"Mixin",
	"NORMAL_FONT_COLOR",
	"ObjectiveTrackerFrame",
	"ObjectiveTrackerManager",
	"OpenWorldMap",
	"ORANGE_FONT_COLOR",
	"Settings",
	"SOUNDKIT",
	"RaidWarningUtil",
	"PlaySound",
	"FlashClientIcon",
	"ChatTypeInfo",
	"UIParent",
	"UiMapPoint",
	"IsShiftKeyDown",
	"GetUnitSpeed",
	"GetTaxiMapID",
	"C_TaxiMap",
	"C_SuperTrack",
	"UnitFactionGroup",
	"UnitName",
	"UnitOnTaxi",
	"UnitPosition",
	"UNKNOWN",
	"WorldMapFrame",
}
files["tests/"] = { std = "+luajit", globals = { "arg" } }
