std = "lua51"
max_line_length = 120
exclude_files = { "tools/.cache/**", ".release/**" }
ignore = { "212/_.*" } -- unused args prefixed with _
globals = { "FerryForeverDB", "FerryForeverDockPinMixin", "SLASH_FERRYFOREVER1", "SlashCmdList" }
read_globals = {
	"Ambiguate",
	"C_ChatInfo",
	"Clamp",
	"C_Map",
	"C_SuperTrack",
	"C_Timer",
	"CreateFrame",
	"CreateFromMixins",
	"CreateVector2D",
	"Enum",
	"GameTooltip",
	"GameTooltip_AddColoredDoubleLine",
	"GameTooltip_AddColoredLine",
	"GameTooltip_AddInstructionLine",
	"GameTooltip_AddNormalLine",
	"GameTooltip_SetTitle",
	"GetNormalizedRealmName",
	"GetRealmName",
	"GetServerTime",
	"GetTime",
	"GRAY_FONT_COLOR",
	"HIGHLIGHT_FONT_COLOR",
	"hooksecurefunc",
	"IsInGroup",
	"IsInGuild",
	"IsInInstance",
	"IsInRaid",
	"LE_PARTY_CATEGORY_INSTANCE",
	"MapCanvasDataProviderMixin",
	"MapCanvasPinMixin",
	"Mixin",
	"NORMAL_FONT_COLOR",
	"ObjectiveTrackerFrame",
	"ObjectiveTrackerManager",
	"OpenWorldMap",
	"Settings",
	"TomTom",
	"UiMapPoint",
	"UIParent",
	"UnitName",
	"UnitOnTaxi",
	"UnitPosition",
	"UNKNOWN",
	"WorldMapFrame",
}
files["tests/"] = { std = "+luajit", globals = { "arg" } }
