-- Walking costs between every pair of fixed places the planner routes through (docks, flight masters, portal
-- ends), searched once here rather than guessed as straight lines and measured in game. Run from the repo root
-- after rebaking a walking map or changing the places: luajit tools/bake_walks.lua > Data/Walks.lua
local ns = { Docks = {}, Routes = {}, TaxiNodes = {}, TaxiPaths = {}, Portals = {} }
for _, file in ipairs({ "Data/Routes.lua", "Data/Transports.lua", "Data/Taxi.lua", "Data/Portals.lua", "Path.lua" }) do
	assert(loadfile(file))("ShortestPathForever", ns)
end
for _, nav in ipairs({
	"ShortestPathForever_Nav0/Nav0.lua",
	"ShortestPathForever_Nav1/Nav1.lua",
	"ShortestPathForever_Nav2991/Nav2991.lua",
}) do
	assert(loadfile(nav))()
end
local Path = ns.Path

local places = {}
local function Add(key, point)
	places[point.map] = places[point.map] or {}
	table.insert(places[point.map], { key = key, point = point })
end
for id, dock in pairs(ns.Docks) do
	Add("dock" .. id, dock)
end
for id, node in pairs(ns.TaxiNodes) do
	Add("taxi" .. id, node)
end
for id, portal in ipairs(ns.Portals) do
	Add("portal" .. (id * 2 - 1), portal.from)
	Add("portal" .. id * 2, portal.to)
end

-- The same box test the planner uses: it never walks between landmasses, so neither does the bake.
local function Landmass(point)
	for index, land in ipairs(ns.Landmasses) do
		if
			point.map == land.map
			and point.x >= land.minX
			and point.x <= land.maxX
			and point.y >= land.minY
			and point.y <= land.maxY
		then
			return index
		end
	end
end

-- Both costs; a dry walk that never touches water costs the same with water walking, so it is searched once.
local function Costs(map, a, b)
	local points, cost = Path.FindSync(map, a, b, false)
	if not points then
		assert(cost == "unreachable", tostring(cost))
		local wet, wetCost = Path.FindSync(map, a, b, true)
		return "false", wet and string.format("%d", wetCost + 0.5) or "false"
	end
	local dry = string.format("%d", cost + 0.5)
	if (points.wet or 0) == 0 then
		return dry, dry
	end
	-- Water walking never forces you into the water, so the dry way bounds it; the search's cluster abstraction can
	-- otherwise find a slightly longer one.
	local wet, wetCost = Path.FindSync(map, a, b, true)
	return dry, wet and string.format("%d", math.min(cost, wetCost) + 0.5) or dry
end

local maps = {}
for map in pairs(places) do
	if Path.HasData(map) then
		maps[#maps + 1] = map
	end
end
table.sort(maps)
print("local _, ns = ...")
print("")
print("-- Generated by tools/bake_walks.lua: running yards between fixed places, { dry, water walking }, false where")
print("-- there is no way through. Keys pair the planner's node keys in sorted order.")
print("ns.Walks = {")
for _, map in ipairs(maps) do
	local list = places[map]
	table.sort(list, function(a, b)
		return a.key < b.key
	end)
	io.stderr:write(("map %d: %d places\n"):format(map, #list))
	print(("\t[%d] = {"):format(map))
	for i = 1, #list do
		for j = i + 1, #list do
			local a, b = list[i], list[j]
			if Landmass(a.point) == Landmass(b.point) then
				local dry, wet = Costs(map, a.point, b.point)
				print(('\t\t["%s %s"] = { %s, %s },'):format(a.key, b.key, dry, wet))
			end
		end
	end
	print("\t},")
end
print("}")
